#! /bin/bash

# Bash Graphical User Theme Changer

version="0.9"

theme=$(sed -n '2p' /home/$(logname)/.config/bgutc.conf)
declare -A path

show_version () {
	echo $version
}

search_paths () {

rep=$1

option=$(sed -n '1p' /home/$(logname)/.config/bgutc.conf)

for val in $option; do
    path["$val"]="hi"
done

current_section=""

while IFS='=' read -r key value; do

    key=$(echo "$key" | xargs)
    value=$(echo "$value" | xargs)

    [[ -z "$key" || "$key" =~ ^# ]] && continue

    if [[ "$key" == \[*\] ]]; then		# Check which is beign read
        current_section="${key:1:-1}"  

    elif [[ -n "$current_section" ]]; then 	
		
		if [[ "$key" = "conf" ]]; then
			path[$current_section]=$value

		elif [[ "$key" = "$rep" ]]; then
			path[$current_section]+=" ""$value"
		fi

    fi
done < /home/$(logname)/.config/bgutc.conf

}

set_change () {
	theme_selected=$1

	search_paths "$theme_selected"

	for key in "${!path[@]}"; do
        echo "$key: ${path[$key]}"
    done

	#string="value1 value2"
	#first_value=$(echo "$string" | cut -d' ' -f1)
	#echo "$first_value"  # Outputs: value1


}

if [ "$1" = "-h" ] || [ "$1" = "--help" ] ; then
	echo "-h, --help 		Display this help and exit"
	echo "-v, --version		Display build version and exit"

elif [ "$1" = "-v" ] || [ "$1" = "--version" ] ; then
	show_version
	
else

theme_selected=$(zenity --list --title="Select Theme" --text="Themes" --column="" $theme)

echo $theme_selected is applied

set_change "$theme_selected"
	

#pkill polybar  
#polybar top & 
#polybar bottom &
#i3-msg restart

fi