#! /bin/bash

# Bash Graphical User Theme Changer

version="1.0"

# Global variables used in the search_paths function
option=$(sed -n '1p' /home/$(logname)/.config/bgutc.conf)
theme=$(sed -n '2p' /home/$(logname)/.config/bgutc.conf)
declare -A path
declare -A argument

show_version () {
	echo $version
}

search_paths () {

rep=$1

for val in $option; do
    path["$val"]="hi"
	argument["$val"]="hi"
done

current_section=""

while IFS='=' read -r key value; do

    key=$(echo "$key" | xargs)
    value=$(echo "$value" | xargs)

    [[ -z "$key" || "$key" =~ ^# ]] && continue

    if [[ "$key" == \[*\] ]]; then		# Check which is beign read
        current_section="${key:1:-1}"  

    elif [[ -n "$current_section" ]]; then 	
		
		if [[ "$key" = "conf" ]]; then
			path[$current_section]=$value

		elif [[ "$key" = "arg" ]]; then
			argument[$current_section]=$value

		elif [[ "$key" = "$rep" ]]; then
			path[$current_section]+=" ""$value"
		fi

    fi
	done < /home/$(logname)/.config/bgutc.conf

	echo path found
}

set_change () {
	theme_selected=$1

	search_paths "$theme_selected"

	for key in "${!path[@]}"; do
        echo "$key: ${path[$key]}"
    done

	for program in "${!path[@]}"; do
		read default_path newconf_path <<< "${path[$program]}"
		rm $default_path
		cp $newconf_path $default_path
	done

}

if [ "$1" = "-h" ] || [ "$1" = "--help" ] ; then
	echo "-h, --help 		Display this help and exit"
	echo "-v, --version		Display build version and exit"

elif [ "$1" = "-v" ] || [ "$1" = "--version" ] ; then
	show_version
	
else

theme_selected=$(zenity --list --title="Select Theme" --text="Themes" --column="" $theme)

echo $theme_selected is applied

set_change "$theme_selected"

# Restart WM

if echo "$option" | grep -wq "i3"; then
	i3-msg restart
fi

if echo "$option" | grep -wq "sway"; then
	swaymsg reload
fi

# Restart Bars

if echo "$option" | grep -wq "polybar"; then
	pkill polybar
	if [[ -n argument[polybar] ]]; then
		IFS=' ' read -r -a array <<< "${argument[polybar]}"
		for item in "${array[@]}"; do
			polybar $item
		done
	else
		polybar
	fi
fi

if echo "$option" | grep -wq "waybar"; then
	pkill -SIGUSR1 waybar
fi

# Restart others

if echo "$option" | grep -wq "dunst"; then
	pkill -SIGUSR1 dunst
fi

fi
